import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'sign_in': 'Sign in',
          'dont_have_account': 'If you don’t have an account register you can',
          'register_here': 'Register here',
          'enter_email': 'Enter your email',
          'email': 'Email',
          'enter_password': 'Enter your password',
          'password': 'Password',
          'forgot_password': 'Forgot Password?',
          'remember_me': 'Remember me',
          'login': 'Login',
          'or_continue_with': 'or continue with',
          'register': 'register',
          'login_here': 'Login here',
          'name': 'Name',
          'i_accept': 'I accept',
          'phone_no': 'phone no',
          'my_cars': 'My Cars',
          'insurance': 'Insurance',
          'contracts': 'Contracts',
          'road_help': 'Road Help',
          'track': 'Track',
          'green_card': 'Green Card',
          'see_insurance': 'See insurance',
          'my_insurance': 'My Insurance',
          'find_new_car': 'Find new car',
          'lease_cars': 'Lease Cars',
          'contract_details': 'Contract Details',
          'term_of_use': 'Term of use',
          'extend': 'Extend',
          'kontrakt_no': 'Kontrakt No',
          'registration_no': 'Registration No',
          'my_contracts': 'My Contracts',
          'track_cars': 'Track cars',
          'my_profile': 'My profile',
          'edit_profile': 'Edit profile',
          'edit': 'Edit',
          'confirm_password': 'Confirm Password',
          'reset_password': 'Reset Password',
          'reset_paragraph':
              'Please enter your new password and confirm password below:',
          'forget_paragraph':
              'Enter your account’s email for which you want to reset your password. We will send you an email with a link to renew your password.',
          'send_link': 'Send Link',
          'forget_password': 'Forget Password',
          'update': 'Update',
          'color_scheme': 'Color Scheme',
          'address': 'Address',
          'dark': 'Dark',
          'terms_and_conditions': 'Terms & Conditions',
          'notifications': 'Notifications',
          'light': 'Light',
          'logout': 'Logout',
          'next': 'Next',
          'current_password': 'Current Password',
          'contact_us': 'Contact us',
          'language': 'Language',
          'save': 'Save',
          'skip': 'Skip',
          'submit_your_request': 'Submit your request',
          'message': 'Message',
          'msg_hint': 'How we can help you?',
          'have_any_question': 'Do you have questions?',
          'locate_us': 'Locate us',
          'write_to_us': 'Write to us',
          'call_us': 'Call us',
          'finish': 'Finish',
          'search': 'Search',
          'select_language': 'Select Language',
          'get_in_touch_with_us': 'Get in Touch with us',
          're_enter_password': 'Re-enter Password',
          'new_password': 'New Password',
          'change_password': 'Change Password',
          'enter_address': 'Enter address',
          'end_kontrakt': 'End Kontrakt',
          'start_kontrakt': 'Start Kontrakt',
          'privacy_policy': 'Privacy Policy',
          'enter_phone': 'Enter your phone no',
          'enter_name': 'Enter your full name',
          'already_have_account': 'If you already have an account?',
          'intro_title_1': 'Lease your car in minutes',
          'intro_title_2': 'Protected with insurance',
          'intro_title_3': 'Track your car in real time',
          'intro_subtitle_1':
              'Aliquam a dui vel justo fringilla euismod id id enim. Nunc non semper tellus. Nunc non semper tellus.',
          'intro_subtitle_2':
              'Aliquam a dui vel justo fringilla euismod id id enim. Nunc non semper tellus. Nunc non semper tellus.',
          'intro_subtitle_3':
              'Aliquam a dui vel justo fringilla euismod id id enim. Nunc non semper tellus. Nunc non semper tellus.',
        },
      };
}
